### PR TITLE
RHMAP-8377 - allow to use file artifact

### PR DESCRIPTION
**Pull request by wtrocki**
Docker build would get artifacts from local folder rather than download it from s3. 

ping @maleck13 @grdryn

### CODE REVIEW

**Comment by grdryn** [comment]
:+1: 

Is any of this useful to the upstream aerogear/dockerfiles project, or do we definitely need a fork here? cc @matzew

**Comment by wtrocki** [comment]
@jasonmadigan changes required to have it forked. Additionally I needed to change approach and provide artifact as local file (which is standard for platform components).
I'm still thinking if we should have it directly in the repo, but we decided to go that way to have track what was changed comparing to upstream.

**Comment by wtrocki** [comment]
Verified on jenkins.

**Comment by wtrocki** [comment]
Reduced number of layers and added some optimizations. Change verified on jenkins.

**Pull request merged**
